# Generated by Django 3.2.16 on 2022-10-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_multitokenauth', '0003_pk_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='multitoken',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='Token name'),
        ),
    ]
